routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/


Route::get('/', ['as' => 'home', 'uses' => 'PagesController@home']);

Route::get('objetive', [
    'as' => 'objetive',
    'uses' => 'PagesController@objetive'
]);

Route::get('experience', [
    'as' => 'experience',
    'uses' => 'PagesController@experience'
]);

Route::get('education', [
    'as' => 'education',
    'uses' => 'PagesController@education'
]);

Route::get('skills', [
    'as' => 'skills',
    'uses' => 'PagesController@skills'
]);

Route::get('contact', [
    'as' => 'contact',
    'uses' => 'PagesController@contact'
]);

//Route::post('sendMail', 'PagesController@sendMail');

// Genera rutas automáticamente para "messages" desde el controlador
Route::resource('messages', 'MessagesController');

// Rutas hacia el login y logout del usuario
Route::get('login', [
    'as'=> 'login',
    'uses' => 'Auth\LoginController@showLoginForm'
]);
Route::post('login', [
    'as'=> 'login',
    'uses' => 'Auth\LoginController@login'
]);
Route::get('logout', [
    'as'=> 'logout',
    'uses' => 'Auth\LoginController@logout'
]);


// Ruta hacia todos los usuarios
Route::resource('users', 'UsersController');


/*
// Almacenar el mensaje en la base de datos
Route::post('messages/store', [
    'as' => 'messages.store',
    'uses' => 'MessagesController@store'
]);

// Mostrar todos los mensajes
Route::get('messages/index', [
    'as' => 'messages.index',
    'uses' => 'MessagesController@index'
]);

// Mostrar un mensaje por ID
Route::get('messages/{id}', [
    'as' => 'messages.show',
    'uses' => 'MessagesController@show'
]);

// Editar un mensaje
Route::get('messages/{id}/edit', [
    'as' => 'messages.edit',
    'uses' => 'MessagesController@edit'
]);

// Actualizar un mensaje
Route::put('messages/{id}', [
    'as' => 'messages.update',
    'uses' => 'MessagesController@update'
]);

// Actualizar un mensaje
Route::delete('messages/{id}', [
    'as' => 'messages.destroy',
    'uses' => 'MessagesController@destroy'
]);

*/

/*
Route::get('/', ['as' => 'home', function () {
    return view('index');
}]);

Route::get('objetive', ['as' => 'objetive', function () {
    return view('objetive');
}]);

Route::get('experience', ['as' => 'experience', function () {
    return view('experience');
}]);

Route::get('education', ['as' => 'education', function () {
    return view('education');
}]);

Route::get('skills', ['as' => 'skills', function () {
    return view('skills');
}]);
*/

resources/views/layouts/app.blade.php
<!DOCTYPE html>
<!--
@author Raúl Caro Pastorino
@copyright Copyright (c) 2018 Raúl Caro Pastorino
@license https://www.gnu.org/licenses/gpl-3.0-standalone.html

Author Web: https://fryntiz.es
E-mail: dev@fryntiz.es
-->

<html lang="es">
@include('layouts.header')

  <body>
    <div id="app" class="row">
        <div id="boxheader">
            @include('layouts.nav')
        </div>

        <div id="boxsidebar" class="col-lg-3 col-md-4 col-sm-12 col-xs-12">
            @include('layouts.sidebar')
        </div>

        <div id="boxcontent" class="col-lg-9 col-md-8 col-sm-12 col-xs-12">
            @if(Session::has('sucess_message'))
                {{ Session::get('sucess_message') }}
            @else
                @yield('content')
            @endif
        </div>

        <div id="boxfooter">
            @include('layouts.footer')
        </div>
    </div>

    @include('layouts.footer-meta')
  </body>
</html>

resources/views/layouts/footer-meta.blade.php
<script type="text/javascript" src="{{ mix('/js/app.js') }}"></script>
<script type="text/javascript" src="{{ mix('/js/footer.js') }}"></script>
<script type="text/javascript" src="{{ mix('/js/afterload.js') }}"></script>
<script type="text/javascript" src="{{ mix('/js/bootstrap.js') }}"></script>
<script type="text/javascript" src="{{ mix('/js/matches-selector.js') }}"></script>
<script type="text/javascript" src="{{ mix('/js/utils.js') }}"></script>
<script type="text/javascript" src="{{ mix('/js/jquery.flexslider.js')}}"></script>
<script type="text/javascript" src="{{ mix('/js/get-size.js')}}"></script>
<script type="text/javascript" src="{{ mix('/js/images-loaded.js')}}"></script>
<script type="text/javascript" src="{{ mix('/js/images-loaded.es.js')}}"></script>
<script type="text/javascript" src="{{ mix('/js/jquery.mb.YTPlayer.js')}}"></script>
<script type="text/javascript" src="{{ mix('/js/jquery.magnific-popup.js')}}"></script>
<script type="text/javascript" src="{{ mix('/js/outlayer.js')}}"></script>
<script type="text/javascript" src="{{ mix('/js/outlayer-item.js')}}"></script>
<script type="text/javascript" src="{{ mix('/js/owl.carousel.js')}}"></script>
<script type="text/javascript" src="{{ mix('/js/jquery.simple-text-rotator.js')}}"></script>
<script type="text/javascript" src="{{ mix('/js/skrollr.min.js')}}"></script>
<script type="text/javascript" src="{{ mix('/js/wow.js')}}"></script>
<script type="text/javascript" src="{{ mix('/js/prettify.js')}}"></script>
<script type="text/javascript" src="{{ mix('/js/SmoothScroll.js')}}"></script>
<script type="text/javascript" src="{{ mix('/js/masonry.js')}}"></script>

resources/views/layouts/footer.blade.php
{{--
@author Raúl Caro Pastorino
@copyright Copyright (c) 2018 Raúl Caro Pastorino
@license https://www.gnu.org/licenses/gpl-3.0-standalone.html

Author Web: https://fryntiz.es
E-mail: dev@fryntiz.es
--}}

<hr class="divider-d" />

<footer class="footer bg-dark">
    <div class="container">
        <div class="row">
            <div class="col-sm-6">
                <div id="footerautor">
                    Raúl Caro Pastorino
                </div>

                <div id="footertechnology">
                    Built with laravel
                </div>

                <p class="copyright font-alt">&copy; 2019 - {{ date('Y') }}
                    <a href="{{ route('home') }}">
                        Curriculum
                    </a>

                    <a href="https://fryntiz.es" target="_blank">
                        Raúl Caro Pastorino
                    </a>
                </p>
            </div>

            <div class="col-sm-6">
                <div class="footer-social-links">
                    <a href="#"><i class="fa fa-facebook"></i></a>
                    <a href="#"><i class="fa fa-twitter"></i></a>
                    <a href="#"><i class="fa fa-telegram"></i></a>
                    <a href="#"><i class="fa fa-google-plus"></i></a>
                </div>
            </div>
        </div>

        <div id="footerlinks" class="row">
            <div class="flinks col-md-4">1</div>
            <div class="flinks col-md-4">2</div>
            <div class="flinks col-md-4">3</div>
        </div>
    </div>
</footer>

{{-- Botón para subir --}}
<div class="scroll-up">
    <a href="#totop"><i class="fa fa-angle-double-up"></i></a>
</div>

resources/views/layouts/header.blade.php
<head>
    <meta charset="utf-8">
    <meta name="description" content="@yield('description')" />
    <meta name="keywords" content="@yield('keywords')" />
    <meta name="author" content="Raúl Caro Pastorino" />
    <meta name="viewport" content="width=device-width, initial-scale=1" />
    <title>@yield('title')</title>
    <link rel="stylesheet" type="text/css" href="{{ mix('/css/app.css') }}" />
    <script type="text/javascript" src="{{ mix('/js/beforeload.js') }}"></script>
    <script type="text/javascript" src="{{ mix('/js/functions.js') }}"></script>
    <script type="text/javascript" src="{{ mix('/js/header.js') }}"></script>
    <meta name="csrf-token" content="{{ csrf_token() }}">

    {{-- CSS --}}

    <!--
    Favicons
    =============================================
    -->
    <!--
    <link rel="apple-touch-icon" sizes="57x57"
          href="{{asset('assets/images/favicons/apple-icon-57x57.png')}}">
    <link rel="apple-touch-icon" sizes="60x60" href="assets/images/favicons/apple-icon-60x60.png">
    <link rel="apple-touch-icon" sizes="72x72" href="assets/images/favicons/apple-icon-72x72.png">
    <link rel="apple-touch-icon" sizes="76x76" href="assets/images/favicons/apple-icon-76x76.png">
    <link rel="apple-touch-icon" sizes="114x114" href="assets/images/favicons/apple-icon-114x114.png">
    <link rel="apple-touch-icon" sizes="120x120" href="assets/images/favicons/apple-icon-120x120.png">
    <link rel="apple-touch-icon" sizes="144x144" href="assets/images/favicons/apple-icon-144x144.png">
    <link rel="apple-touch-icon" sizes="152x152" href="assets/images/favicons/apple-icon-152x152.png">
    <link rel="apple-touch-icon" sizes="180x180" href="assets/images/favicons/apple-icon-180x180.png">
    <link rel="icon" type="image/png" sizes="192x192" href="assets/images/favicons/android-icon-192x192.png">
    <link rel="icon" type="image/png" sizes="32x32" href="assets/images/favicons/favicon-32x32.png">
    <link rel="icon" type="image/png" sizes="96x96" href="assets/images/favicons/favicon-96x96.png">
    <link rel="icon" type="image/png" sizes="16x16" href="assets/images/favicons/favicon-16x16.png">
    <link rel="manifest" href="/manifest.json">
    <meta name="msapplication-TileColor" content="#ffffff">
    <meta name="msapplication-TileImage" content="assets/images/favicons/ms-icon-144x144.png">
    <meta name="theme-color" content="#ffffff">
    -->
    <!--
    Stylesheets
    =============================================

    -->

    {{-- BOOTSTRAP --}}


    <!-- Default stylesheets-->
    <!--
    <link href="assets/lib/bootstrap/dist/css/bootstrap.min.css" rel="stylesheet">
    -->

    <!-- Template specific stylesheets-->
    <link href="https://fonts.googleapis.com/css?family=Roboto+Condensed:400,700"
          rel="stylesheet">
    <link href="https://fonts.googleapis.com/css?family=Volkhov:400i"
          rel="stylesheet">
    <link href="https://fonts.googleapis.com/css?family=Open+Sans:300,400,600,700,800"
          rel="stylesheet">
    <!--

    <link href="assets/lib/animate.css/animate.css" rel="stylesheet">
    <link href="assets/lib/components-font-awesome/css/font-awesome.min.css" rel="stylesheet">
    <link href="assets/lib/et-line-font/et-line-font.css" rel="stylesheet">
    <link href="assets/lib/flexslider/flexslider.css" rel="stylesheet">
    <link href="assets/lib/owl.carousel/dist/assets/owl.carousel.min.css" rel="stylesheet">
    <link href="assets/lib/owl.carousel/dist/assets/owl.theme.default.min.css" rel="stylesheet">
    <link href="assets/lib/magnific-popup/dist/magnific-popup.css" rel="stylesheet">
    <link href="assets/lib/simple-text-rotator/simpletextrotator.css" rel="stylesheet">
    -->

    <!-- Main stylesheet and color file-->
    <!--
    <link href="assets/css/style.css" rel="stylesheet">
    <link id="color-scheme" href="assets/css/colors/default.css" rel="stylesheet">
    -->
</head>

resources/views/layouts/nav.blade.php
{{--
@author Raúl Caro Pastorino
@copyright Copyright (c) 2018 Raúl Caro Pastorino
@license https://www.gnu.org/licenses/gpl-3.0-standalone.html

Author Web: https://fryntiz.es
E-mail: dev@fryntiz.es
--}}

<?php
    /**
     * Comprueba si la url recibida es la actual y devuelve la clase css que se
     * aplicará en cada situación.
     * @param  String $url Ruta URL a comparar.
     * @return String      Nombre de la clase que se aplicará.
     */
    function activeMenu($url):String
    {
        return request()->is($url) ? 'menuActive' : 'menuInactive';
    }

    /**
     * Comprueba si la url recibida es la actual y devuelve la clase css que se
     * aplicará en cada situación para el submenú.
     * @param  String $url Ruta URL a comparar.
     * @return String      Nombre de la clase que se aplicará.
     */
    function activeSubMenu($url):String
    {
        return request()->is($url) ? 'subMenuActive' : 'subMenuInactive';
    }


    /* Array con datos para cada entrada del menú */
    $datosLinks = [
        [   // Inicio
            'section' => trans('sections.home'),
            'url' => '/',
            'link' => route('home')
        ],
        [   // Objetivos
            'section' => trans('sections.objetive'),
            'url' => 'objetive',
            'link' => route('objetive')
        ],
        [   // Experiencia
            'section' => trans('sections.experience'),
            'url' => 'experience',
            'link' => route('experience')
        ],
        [   // Educación
            'section' => trans('sections.education'),
            'url' => 'education',
            'link' => route('education')
        ],
        [   // Habilidades
            'section' => trans('sections.skills'),
            'url' => 'skills',
            'link' => route('skills')
        ],
    ];

    // Idiomas
    $datalang = [
        [
            'id' => 'lang_spanish',
            'abb' => 'es',
            'img' => '/images/languages/es.png',
            'title' => 'Idioma Español',
            'alt' => 'Idioma Español'
        ],
        [
            'id' => 'lang_english',
            'abb' => 'en',
            'img' => '/images/languages/en.png',
            'title' => 'Language English',
            'alt' => 'Language English'
        ],
    ];
?>

<div id="boxheader" class="content-fluid">
    {{-- TopBar --}}
    <nav class="navbar navbar-default" role="navigation">
        <div class="navbar-header">
            <button type="button"
                    class="navbar-toggle"
                    data-toggle="collapse"
                    data-target=".navbar-collapse">
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
        </div>

        <div class="container-fluid">
            <div class="collapse navbar-collapse" id="navbar">
                <ul class="nav navbar-nav">
                    <li>
                        <a href="https://fryntiz.es" target="_blank">
                            {{ trans('sections.portal') }}
                        </a>
                    </li>

                    <li class="{{ activeSubMenu('downloads') }}">
                        <a href="{{-- route('downloads') --}}">
                            {{ trans('sections.downloads') }}
                        </a>
                    </li>
                </ul>

                <ul class="nav navbar-nav navbar-center boxlanguage">
                    @foreach ($datalang as $lang)
                        <li id="{{ $lang['id'] }}">
                            <img src="{{ asset($lang['img']) }}"
                                 title="{{ $lang['title'] }}"
                                 alt="{{ $lang['alt'] }}" />
                            {{ $lang['abb'] }}
                        </li>
                    @endforeach
                </ul>

                {{-- Menú a la Derecha --}}
                <ul class="nav navbar-nav navbar-right">
                    <li class="{{ activeSubMenu('contact') }}">
                        <a href="{{ route('contact') }}">
                            {{ trans('sections.contact') }}
                        </a>
                    </li>

                    @if (auth()->guest())
                        <li class="{{ activeSubMenu('login') }}">
                            <a href="{{ route('login') }}">
                                {{ trans('sections.login') }}
                            </a>
                        </li>

                    @elseif (auth()->check())
                        {{-- Solo administradores pueden ver usuarios --}}
                        @if (auth()->user()->hasRoles(['admin']))
                            <li class="{{ activeSubMenu('users*') }}">
                                <a href="{{ route('users.index') }}">
                                    {{ trans('sections.users') }}
                                </a>
                            </li>
                        @endif

                        <li class="{{ activeSubMenu('messages*') }}">
                            <a href="{{ route('messages.index') }}">
                                {{ trans('sections.messages') }}
                            </a>
                        </li>

                        <li>
                            <a href="{{ route('logout') }}">
                                Cerrar sesión de: {{ auth()->user()->name}}
                            </a>
                        </li>
                    @endif
                </ul>
            </div>
        </div>
    </nav>{{-- /TopBar --}}

    <header class="row">
        {{-- Caja con el título y logotipo --}}
        <div id="boxlogo" class="align-middle col-lg-5 col-md-12 col-sm-12 col-xs-12">
            <figure id="logotipo" class="col-lg-4">
                <img src="{{ asset('/images/logotipo.png') }}"
                     alt="Logo"
                     title="Logo" />
            </figure>
            <h1 id="sitetitle" class="col-lg-8">@yield('title')</h1>
        </div>

        {{-- Botón que indica desplegable en pantallas pequeñas --}}
        <div id="btnMovil" class="col-lg-0 col-md-0 col-sm-0 col-xs-12">
          <span class="fa fa-bars"></span>
        </div>

        {{-- Enlaces de navegación --}}
        <nav class="col-lg-7 col-md-12 col-sm-12 col-xs-12">
            <ul>
                @foreach ($datosLinks as $sectionlink)
                    <li class="col-lg-2 col-md-2 col-sm-12 col-xs-12">
                        <a class="{{ activeMenu($sectionlink['url']) }}"
                           href="{{ $sectionlink['link'] }}">
                            {{ $sectionlink['section'] }}
                        </a>
                    </li>
                @endforeach
            </ul>
        </nav>
    </header>
</div>

resources/views/layouts/sidebar.blade.php
{{--
@author Raúl Caro Pastorino
@copyright Copyright (c) 2018 Raúl Caro Pastorino
@license https://www.gnu.org/licenses/gpl-3.0-standalone.html

Author Web: https://fryntiz.es
E-mail: dev@fryntiz.es
--}}
<aside>
    Este es el sidebar
</aside>